server:
  port: 8060
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eurekaServer/eureka/
spring:
  application:
    name: customer-service
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616